### ISSUE TITLE
无法使用查询玩家战绩命令

### ISSUE THREAD

**Issue by johnsilverhand** [Shennoter/ApexRankLookUp#13]
java版本:17
MCL版本:2.1.0
插件版本:1.4.1
出错命令:/apexid
2022-05-28 17:45:47 W/ApexLookUp: Exception in executing command `[mirai:source:[1393],[1506089929]]/apexid vangams233`
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:329)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: javax.imageio.IIOException: Can't get input stream from URL!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407)
        at ranklookup-1.4.1.mirai.jar//pers.shennoter.ApexImageKt.ImageCache(ApexImage.kt:28)
        at ranklookup-1.4.1.mirai.jar//PlayerStatKt.playerPicturMode(PlayerStat.kt:46)
        at ranklookup-1.4.1.mirai.jar//PlayerStatKt.playerStat(PlayerStat.kt:34)
        at ranklookup-1.4.1.mirai.jar//Player.apexPlayerInfo(Commands.kt:22)
        ... 27 more
Caused by: java.io.FileNotFoundException: https://api.mozambiquehe.re/assets/banners/newcastle.jpg
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at java.base/java.net.URL.openStream(URL.java:1165)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1405)
        ... 31 more

**Comment by Shennoter** [comment]
`Caused by: java.io.FileNotFoundException: https://api.mozambiquehe.re/assets/banners/newcastle.jpg`
查询的这个人主界面传奇是纽卡斯尔，这个问题要等api提供者修复，想查询的话把主界面传奇换成其他人就行了

**Comment by Shennoter** [comment]
晚上修一下

**Comment by Shennoter** [comment]
已修复
