### ISSUE TITLE
[Bug]查询玩家信息时出错

### ISSUE THREAD

**Issue by Evyde** [Shennoter/ApexRankLookUp#14]
查询玩家时提示如下，且只有查询玩家相关功能时出错，其他功能（例如地图轮换）正常。
已经尝试删除`data/`文件夹下所有相关数据并删除插件重新安装，无效。
在插件刚装好（但字体配置有误）时是可以正常使用的。
mirai: 2.11.0
mirai-console: 2.11.0
chat-command: 0.5.1
插件版本: 1.5.1
报错信息：
```
2022-06-14 22:56:40 W/ApexLookUp: Exception in executing command `[mirai:source:[4596],[1192419039]]/apexid XXXXX`
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:329)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NullPointerException: Cannot invoke "Global.getRank()" because the return value of "ApexResponsePlayer.getGlobal()" is null
        at ranklookup-1.5.1.mirai.jar//PlayerStatKt.playerPicturMode(PlayerStat.kt:44)
        at ranklookup-1.5.1.mirai.jar//PlayerStatKt.playerStat(PlayerStat.kt:34at ranklookup-1.5.1.mirai.jar//Player.apexPlayerInfo(Commands.kt:19)
        ... 27 more
```
顺便，在查询轮换地图时好像也有问题：
```
2022-06-14 22:34:08 W/stderr:   at com.google.gson.Gson.fromJson(Gson.java:897)
2022-06-14 22:34:08 W/stderr:   at com.google.gson.Gson.fromJson(Gson.java:846)
2022-06-14 22:34:08 W/stderr:   at com.google.gson.Gson.fromJson(Gson.java:817)
2022-06-14 22:34:08 W/stderr:   at ranklookup-1.5.1.mirai.jar//pers.shennoter.MapReminderKt$mapReminder$mapTask$1.run(MapReminder.kt:63)
2022-06-14 22:34:08 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Timer.java:566)                                                                     
2022-06-14 22:34:08 W/stderr:   at java.base/java.util.TimerThread.run(Timer.java:516)                                                                          
2022-06-14 22:34:08 W/stderr: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $                        
2022-06-14 22:34:08 W/stderr:   at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)                                                           
2022-06-14 22:34:08 W/stderr:   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)               
2022-06-14 22:34:08 W/stderr:   ... 7 more 
```

 - [x] 对所有返回值进行非Null检查
 - [x] 在查询不到时更换不同平台进行查询

**Comment by Shennoter** [comment]
浏览器输入
https://api.mozambiquehe.re/maprotation?version=2&auth= `${apikey}`
检查一下apikey的有效性

其实这个问题我也不是很清楚为什么。从StackTrace来看是完成了接收响应包这一步，然后到了生成图片读取响应包中的数据时读到了null。但是我在从发请求到判断响应包状态码都有相应的异常处理，一个空数据是怎样绕过这些异常处理来到图片生成环节的，我还没搞清楚。其他人也偶尔会有这种问题，有的人是config里的User.json多了个问号，大部分都是过一段时间突然就没问题，很玄学
主要是这个问题我没碰到过，也没办法复现

**Comment by Evyde** [comment]
API正常，毕竟是昨天刚刚申请的。
## 原因分析
刚刚看了下代码，大概清楚是怎么回事了：
首先，当玩家“不存在”时（应该是存在的，比如XBox用户），API会返回一个HTTP Code为200 OK的Error Message：
```json
{"Error":"Player XXXXX not found (code 103 - skipping origin backup api)"}
```
如图：
<img width="191" alt="image" src="https://user-images.githubusercontent.com/9302540/173733062-35a858b1-4374-4935-a237-4e8d8d89819a.png">
而`utils/GetResponse.kt`中的[Line 34-44](https://github.com/Shennoter/ApexRankLookUp/blob/ffa0fdaeeff1325da6c722bbcf3345c99b350b65/src/main/kotlin/utils/GetResponse.kt#L34-L44)只对Response的HTTP Code进行了判断。
https://github.com/Shennoter/ApexRankLookUp/blob/ffa0fdaeeff1325da6c722bbcf3345c99b350b65/src/main/kotlin/utils/GetResponse.kt#L34-L44
并且[拿到`getRes()`返回值的`playerStat()`方法](https://github.com/Shennoter/ApexRankLookUp/blob/ffa0fdaeeff1325da6c722bbcf3345c99b350b65/src/main/kotlin/functions/PlayerStat.kt#L24)只对构造的返回代码进行了校验，没有进行额外的判断。
https://github.com/Shennoter/ApexRankLookUp/blob/ffa0fdaeeff1325da6c722bbcf3345c99b350b65/src/main/kotlin/functions/PlayerStat.kt#L24
换句话说，`getRes()`返回的body是被信任的，但实际不应该如此。
然后就是[`playerStat()`的Line 32](https://github.com/Shennoter/ApexRankLookUp/blob/ffa0fdaeeff1325da6c722bbcf3345c99b350b65/src/main/kotlin/functions/PlayerStat.kt#L32)，直接调用`Gson()`进行构造：
https://github.com/Shennoter/ApexRankLookUp/blob/ffa0fdaeeff1325da6c722bbcf3345c99b350b65/src/main/kotlin/functions/PlayerStat.kt#L32
Gson在找不到对应key的value时，会将相应变量置null，但由于您使用了`ApexResponsePlayer`类，`res`变量本身不为null，同时您也没有对Gson的返回值进行判断，而是直接调用了`playerPicturMode()`，
https://github.com/Shennoter/ApexRankLookUp/blob/ffa0fdaeeff1325da6c722bbcf3345c99b350b65/src/main/kotlin/functions/PlayerStat.kt#L34
这个方法并没有对传入的res变量做非null检查，仅进行了类型约束，所以会在访问`res.global`的时候抛出NullPointerException。
https://github.com/Shennoter/ApexRankLookUp/blob/ffa0fdaeeff1325da6c722bbcf3345c99b350b65/src/main/kotlin/functions/PlayerStat.kt#L44

鉴于我昨天是正常查询了的，所以我估计API在首次探测的时候不会检测平台，这也是当`platform`设置为`PC`能够正常查询的原因。但当API那边有了缓存之后，用`platform`为PC的值就查不到了。

## 修改建议
- [x] 对所有返回值进行非Null检查，类似：

```java
try {
    if (res == null || res.global == null || res.global.rank == null || res.global.rank.rankName == null) {
        throw new RuntimeException();
    }
} catch (RuntimeException re) {
    return ...;
}
```
可能Kotlin有更好的做法，我不了解Kotlin就不做评价了。
我记得Gson也可以定义找到null时候的行为。
- [x] 在查询不到时更换不同平台进行查询

**Comment by Shennoter** [comment]
原来是这样，感谢，其实这个返回状态码200错误信息的问题，我在[v1.4.0](https://github.com/Shennoter/ApexRankLookUp/releases/tag/v1.4.0)以前的版本是用一个ApexResponseError的类来处理的（很简单粗暴）
https://github.com/Shennoter/ApexRankLookUp/blob/a0d352c42057aa6c7431801a4bb122d876888802/src/main/kotlin/ApexResponseError.kt#L3-L5
https://github.com/Shennoter/ApexRankLookUp/blob/a0d352c42057aa6c7431801a4bb122d876888802/src/main/kotlin/PlayerStat.kt#L36-L41
在v1.4.0写了一个专门用来请求数据的方法后就忘记这种情况的处理了，在v1.5.1发布后其实我有注意到这个问题，并且已经在idea写好了准备多积累几个bug一起发布，由于没有把这个问题和这个bug联系起来，我就没有单独更新
```kotlin
  return when(response.code){
      200 -> {
          if (body?.contains("Error") == true) {
              Pair(1,"错误：" + body.split("\"")[3]) //{"Error":"Player /apexmap not found (code 103 - skipping origin backup api)"} 总有人会输入一些意料之外的数据
          } else {
              Pair(0, body)
          }
      }
      400 -> Pair(1, "请重试")
      403 -> Pair(1, "API key无权限或不存在")
      404 -> Pair(1, "玩家不存在")
      405 -> Pair(1, "玩家存在但从未玩过APEX")
      410 -> Pair(1, "未知平台")
      429 -> Pair(1, "API过热，请稍后再试")
      500 -> Pair(1, "API服务器内部错误")
      else -> Pair(1, "未知错误")
  }
```
您的两个建议将会在下次更新实现，谢谢！

**Comment by Evyde** [comment]
> 原来是这样，感谢，其实这个返回状态码200错误信息的问题，我在[v1.4.0](https://github.com/Shennoter/ApexRankLookUp/releases/tag/v1.4.0)以前的版本是用一个ApexResponseError的类来处理的（很简单粗暴）
> 
> https://github.com/Shennoter/ApexRankLookUp/blob/a0d352c42057aa6c7431801a4bb122d876888802/src/main/kotlin/ApexResponseError.kt#L3-L5
> 
> 
> https://github.com/Shennoter/ApexRankLookUp/blob/a0d352c42057aa6c7431801a4bb122d876888802/src/main/kotlin/PlayerStat.kt#L36-L41
> 
> 
> 在v1.4.0写了一个专门用来请求数据的方法后就忘记这种情况的处理了，在v1.5.1发布后其实我有注意到这个问题，并且已经在idea写好了准备多积累几个bug一起发布，由于没有把这个问题和这个bug联系起来，我就没有单独更新
> ```kotlin
>   return when(response.code){
>       200 -> {
>           if (body?.contains("Error") == true) {
>               Pair(1,"错误：" + body.split("\"")[3]) //{"Error":"Player /apexmap not found (code 103 - skipping origin backup api)"} 总有人会输入一些意料之外的数据
>           } else {
>               Pair(0, body)
>           }
>       }
>       400 -> Pair(1, "请重试")
>       403 -> Pair(1, "API key无权限或不存在")
>       404 -> Pair(1, "玩家不存在")
>       405 -> Pair(1, "玩家存在但从未玩过APEX")
>       410 -> Pair(1, "未知平台")
>       429 -> Pair(1, "API过热，请稍后再试")
>       500 -> Pair(1, "API服务器内部错误")
>       else -> Pair(1, "未知错误")
>   }
> ```
> 
> 您的两个建议将会在下次更新实现，谢谢！

感谢及时修复。

**Comment by Evyde** [comment]
好快的修！
但是多平台查询好像没实现？在返回103之后就直接错误了，要不要弄个循环试试？
@Shennoter

**Comment by Shennoter** [comment]
> 好快的修！ 但是多平台查询好像没实现？在返回103之后就直接错误了，要不要弄个循环试试？ @Shennoter

有其他平台的id吗，测试一下

**Comment by Evyde** [comment]
> > 好快的修！ 但是多平台查询好像没实现？在返回103之后就直接错误了，要不要弄个循环试试？ @Shennoter
> 
> 有其他平台的id吗，测试一下

没找到您的私聊方式，放到了[这里](https://pastebin.pl/view/6c3bab8d)（阅后即焚）。

**Comment by Shennoter** [comment]
我在我的机器人试了一下，正常输出了图片，在PS排行榜找了排名第一的id试了一下，也可以正常输出图片（确认过帐号是没有PC平台的）

**Comment by Evyde** [comment]
> 我在我的机器人试了一下，正常输出了图片，在PS排行榜找了排名第一的id试了一下，也可以正常输出图片（确认过帐号是没有PC平台的）

我说的情况就是这个，第一次应该是服务器没有缓存所以用PC的可以查，但是第二次之后就不行了，提示未找到。必须把platform参数换成对应平台才行。

**Comment by Shennoter** [comment]
emm，我刚刚连续查询了五次都是有正常返回的，又试了一下中途查询其他id再继续查询此id，都是正常输出
https://github.com/Shennoter/ApexRankLookUp/blob/8e96b0839f1fdf0f098c7d818e63e63b1fe164aa/src/main/kotlin/functions/PlayerStat.kt#L18-L25
不过确实也可以通过加一个循环来代替额外apikey的作用
突然又想到，如果在有几个人同时查询的情况下，加循环可能会导致死锁吧，注册过的apikey查询频率限制是2次/秒（好像又不会）

**Comment by Evyde** [comment]
> emm，我刚刚连续查询了五次都是有正常返回的，又试了一下中途查询其他id再继续查询此id，都是正常输出
> 
> https://github.com/Shennoter/ApexRankLookUp/blob/8e96b0839f1fdf0f098c7d818e63e63b1fe164aa/src/main/kotlin/functions/PlayerStat.kt#L18-L25
> 
> 
> 不过确实也可以通过加一个循环来代替额外apikey的作用
> 突然又想到，如果在有几个人同时查询的情况下，加循环可能会导致死锁吧，注册过的apikey查询频率限制是2次/秒（好像又不会）

PS榜这几位PC号和PS4号都用的一个账号名，但是等级不一样，可以看到不同的内容：
<img width="314" alt="image" src="https://user-images.githubusercontent.com/9302540/173814476-25ac6d43-0958-40f9-8c82-c1ac46e24f61.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/9302540/173814523-75bf7af4-6f40-4cf6-a883-dfe4fbbdd502.png">

所以和我说的不太一样。我说的是那种Xbox/PS Only的情况，比如这个人：
`dino771008`
<img width="299" alt="image" src="https://user-images.githubusercontent.com/9302540/173814784-093cfcf6-83e7-45f2-9051-449f511de43b.png">
PS有他的信息，但是PC没有，提示102
<img width="606" alt="image" src="https://user-images.githubusercontent.com/9302540/173814833-c1de8559-2fa2-4bb0-ae65-7e7d05fcdf2f.png">
所以其实修改建议是把全平台查一遍，然后发三张图或者三块儿拼成一个图，这样可以避免同一个用户名在不同平台有不同进度的问题。

**Comment by Shennoter** [comment]
那我下次直接给/apexid加一个平台参数，不输入的话就默认是PC
config加一个默认平台，应对不同平台的用户群

**Comment by Evyde** [comment]
> 那我下次直接给/apexid加一个平台参数，不输入的话就默认是PC

这看您了，我觉得可能查三个平台然后发三张图更简单一点（

**Comment by Evyde** [comment]
哦对了，/apexid看起来正常，我一直都是拿/apexadd id试的。这个会报错。

**Comment by Shennoter** [comment]
> 哦对了，/apexid看起来正常，我一直都是拿/apexadd id试的。这个会报错。

嘶，忘记在/apexadd id处理200状态码的错误了

**Comment by Shennoter** [comment]
这下应该没问题了吧

**Comment by Evyde** [comment]
> 这下应该没问题了吧

```java
2022-06-16 22:55:59 W/ApexLookUp: Exception in executing command `[mirai:source:[],[]]/apexadd id XXXXX`
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at ranklookup-1.5.3.mirai.jar//pers.shennoter.PlayerListenerKt.playerStatListener(PlayerListener.kt:47)
        at ranklookup-1.5.3.mirai.jar//pers.shennoter.PlayerListenerKt$playerStatListener$1.invokeSuspend(PlayerListener.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        ... 12 more
```

**Comment by Shennoter** [comment]
release重新上传了

**Comment by Evyde** [comment]
> release重新上传了

应该没问题了，测了几天都是正常使用的。
